version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    commit_message:
      prefix: "chore"
      include_scope: true
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    commit_message:
      prefix: "chore"
      include_scope: true
